apiVersion: v1
kind: PersistentVolume
metadata:
  name: fpknebel-zookeeper-data
spec:
  storageClassName: fpknebel-local-storage
  capacity:
    storage: 250Mi
  accessModes:
  - ReadWriteOnce
  local:
    path: /mnt/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - nodetype=server
