apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-connect
  name: kafka-connect
spec:
  selector:
    service: kafka-connect
  ports:
    - name: internal
      port: 8083
      targetPort: 8083
    # - name: external
    #   port: 30092
    #   targetPort: 9092
    #   nodePort: 30092
  type: NodePort
